CREATE TABLE "moodScore" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "moodScore_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"createdBy" integer,
	"anxietyLevel" integer DEFAULT 0 NOT NULL,
	"lowMoodLevel" integer DEFAULT 0 NOT NULL,
	"contentmentLevel" integer DEFAULT 0 NOT NULL,
	"frustrationLevel" integer DEFAULT 0 NOT NULL,
	"excitementLevel" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
ALTER TABLE "moodScore" ADD CONSTRAINT "moodScore_createdBy_users_id_fk" FOREIGN KEY ("createdBy") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;