CREATE TABLE "diaryEntry" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "diaryEntry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"createdBy" integer,
	"selfRating" integer NOT NULL,
	"text" varchar(256),
	"createdAt" date DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "diaryEntry" ADD CONSTRAINT "diaryEntry_createdBy_users_id_fk" FOREIGN KEY ("createdBy") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;